version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todobackend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fjxizzdjhtpj"
s3_prefix = "todobackend"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
